import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { SessionProvider } from "next-auth/react";
import ClientProvider from "./components/ClientProvider";
import { Analytics } from "@vercel/analytics/react";

//import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body>
        <ClientProvider>{children}</ClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
